/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JTextField;
import view.PenjualanVIew;
/**
 *
 * @author Riski Dwi
 */
public class isiTanki extends javax.swing.JFrame {

    /**
     * Creates new form isiTanki
     */
    public isiTanki() {
        initComponents();
    }
    
    public JTextField getTankiField(){
        
        return txtInputTanki;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_nama_keuntungan4 = new javax.swing.JLabel();
        txtInputTanki = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn_simpan_Tanki = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(44, 148, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nama_keuntungan4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_nama_keuntungan4.setForeground(new java.awt.Color(255, 255, 255));
        Label_nama_keuntungan4.setText("Masukan Harga Air Per Tanki");
        jPanel1.add(Label_nama_keuntungan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 29));

        txtInputTanki.setBackground(new java.awt.Color(44, 148, 230));
        txtInputTanki.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtInputTanki.setForeground(new java.awt.Color(255, 255, 255));
        txtInputTanki.setBorder(null);
        txtInputTanki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputTankiActionPerformed(evt);
            }
        });
        txtInputTanki.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputTankiKeyTyped(evt);
            }
        });
        jPanel1.add(txtInputTanki, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 225, 40));

        jPanel2.setBackground(new java.awt.Color(219, 236, 248));

        btn_simpan_Tanki.setBackground(new java.awt.Color(44, 148, 230));
        btn_simpan_Tanki.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan_Tanki.setText("Simpan");
        btn_simpan_Tanki.setBorder(null);
        btn_simpan_Tanki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_TankiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(btn_simpan_Tanki, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_simpan_Tanki, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 230, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputTankiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputTankiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputTankiActionPerformed

    private void btn_simpan_TankiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_TankiActionPerformed
            // TODO add your handling code here:
        
        getTankiField();
        PenjualanVIew penjualan = new PenjualanVIew();
        penjualan.isiTanki(getTankiField().getText());
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btn_simpan_TankiActionPerformed

    private void txtInputTankiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputTankiKeyTyped
        // TODO add your handling code here:
         char ketikan = evt.getKeyChar();
        if (!(Character.isDigit(ketikan))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtInputTankiKeyTyped
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_nama_keuntungan4;
    private javax.swing.JButton btn_simpan_Tanki;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtInputTanki;
    // End of variables declaration//GEN-END:variables
}
