/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static database.RizkyBaruDatabase.getConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.lang.String;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTextField;

/**
 *
 * @author Riski Dwi
 */
public class LoginView extends javax.swing.JFrame {

    
    
    
    public JTextField getTxtPassword() {
        
        return txtPassword;
    }

    /**
     * Creates new form LoginView
     */
    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LayerUtama = new javax.swing.JPanel();
        Label_nama_keuntungan6 = new javax.swing.JLabel();
        Label_nama_keuntungan5 = new javax.swing.JLabel();
        PanelForm = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        labelusername = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        labelusername1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Ke Dashboard Rizky Baru");
        setPreferredSize(new java.awt.Dimension(408, 595));
        setResizable(false);
        setSize(new java.awt.Dimension(408, 595));

        LayerUtama.setBackground(new java.awt.Color(219, 236, 248));
        LayerUtama.setForeground(new java.awt.Color(219, 236, 248));
        LayerUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nama_keuntungan6.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        Label_nama_keuntungan6.setForeground(new java.awt.Color(44, 148, 230));
        Label_nama_keuntungan6.setText("Baru");
        LayerUtama.add(Label_nama_keuntungan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 90, -1));

        Label_nama_keuntungan5.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Label_nama_keuntungan5.setForeground(new java.awt.Color(44, 148, 230));
        Label_nama_keuntungan5.setText("Rizky");
        LayerUtama.add(Label_nama_keuntungan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        PanelForm.setBackground(new java.awt.Color(44, 148, 230));
        PanelForm.setForeground(new java.awt.Color(255, 255, 255));
        PanelForm.setPreferredSize(new java.awt.Dimension(408, 595));

        btnLogin.setBackground(new java.awt.Color(44, 148, 230));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnLogin.setContentAreaFilled(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUsername.setBackground(new java.awt.Color(44, 148, 230));
        txtUsername.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setBorder(null);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        labelusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelusername.setForeground(new java.awt.Color(255, 255, 255));
        labelusername.setText("Username");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        labelusername1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelusername1.setForeground(new java.awt.Color(255, 255, 255));
        labelusername1.setText("Password");

        txtPassword.setBackground(new java.awt.Color(44, 148, 230));
        txtPassword.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelFormLayout = new javax.swing.GroupLayout(PanelForm);
        PanelForm.setLayout(PanelFormLayout);
        PanelFormLayout.setHorizontalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFormLayout.createSequentialGroup()
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelusername1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelusername, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsername)
                                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                .addComponent(jSeparator1)))
                        .addGap(62, 62, 62))
                    .addGroup(PanelFormLayout.createSequentialGroup()
                        .addGroup(PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        PanelFormLayout.setVerticalGroup(
            PanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFormLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(labelusername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelusername1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        LayerUtama.add(PanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 420, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayerUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LayerUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        this.con=con;
        String selectUntung = "SELECT username,password FROM user WHERE id_user=1" ;
        Statement statement = null;
        String ambilPassword,ambilUsername,inputUser,inputPassword;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            ambilUsername = result.getString("username");
            ambilPassword = result.getString("password");
            
            inputPassword = getTxtPassword().getText();
            inputUser = getTxtUsername().getText();
            System.out.println(ambilPassword);
            if ( (inputUser.equalsIgnoreCase(ambilUsername) ) && (inputPassword.equals(ambilPassword) ) ) {
                
                try {
                    MainViewPenjualan Penjualan = new MainViewPenjualan();
                    this.setVisible(false);
                    Penjualan.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Login Berhasil!");
                    
                } catch (Exception e) {
                }
                
            }else{
                JOptionPane.showMessageDialog(this, "Username atau Password Salah!");
            }
            
    
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
        }
       
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }
    private Connection con;
    
    public void ambilUser(){
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_nama_keuntungan5;
    private javax.swing.JLabel Label_nama_keuntungan6;
    private javax.swing.JPanel LayerUtama;
    private javax.swing.JPanel PanelForm;
    private javax.swing.JButton btnLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelusername;
    private javax.swing.JLabel labelusername1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
