/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import controller.PenjualanController;
import database.KoneksiJasper;
import database.RizkyBaruDatabase;
import static database.RizkyBaruDatabase.getConnection;
import entity.Penjualan;
import error.PenjualanException;
import event.PenjualanListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import model.PenjualanModel;
import model.TabelPenjualanModel;
import service.PenjualanDao;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.JXDatePicker;
import view.isiTanki;

/**
 *
 * @author Rizki Adam Kurniawan
 */
public class PenjualanVIew extends javax.swing.JPanel implements PenjualanListener, ListSelectionListener {

    private TabelPenjualanModel tabelModel;
    private PenjualanModel model;
    private PenjualanController controller;
    private Object jLabel;

    public PenjualanVIew() {
        tabelModel = new TabelPenjualanModel();

        model = new PenjualanModel();
        model.setListener(this);

        controller = new PenjualanController();
        controller.setModel(model);

        initComponents();
        tablePenjualan.getSelectionModel().addListSelectionListener(this);

        tablePenjualan.setModel(tabelModel);
        
        //ambil value dari tabel
        tampilUntung();
        tampilGalon();
        tampilTankiSatuan();
        tampilTanki();
        
        txtTgl.setVisible(false);
        
       
    }

    public JTable getTablePenjualan() {
        return tablePenjualan;
    }

    public JTextField getTxtGalon() {
        return txtGalon;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtTgl() {
        return txtTgl;
    }

    public JTextField getTxtJumlah() {
        return txtJumlah;
    }
    
   
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        PanelUtama = new javax.swing.JPanel();
        PanelUntungBulan = new javax.swing.JPanel();
        lblTampilUntung = new javax.swing.JLabel();
        Label_nama_keuntungan5 = new javax.swing.JLabel();
        Label_tampiUntung5 = new javax.swing.JLabel();
        PanelInput = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        txtTgl = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtGalon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        tanggal = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        Label_nama_keuntungan11 = new javax.swing.JLabel();
        PanelTabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenjualan = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        Label_nama_keuntungan9 = new javax.swing.JLabel();
        PanelUntungBulan3 = new javax.swing.JPanel();
        lblTampilTanki = new javax.swing.JLabel();
        Label_nama_keuntungan10 = new javax.swing.JLabel();
        Label_tampiUntung6 = new javax.swing.JLabel();
        PanelUntungBulan4 = new javax.swing.JPanel();
        Label_tampiUntung3 = new javax.swing.JLabel();
        lblTampilTankiSatuan = new javax.swing.JLabel();
        Label_nama_keuntungan = new javax.swing.JLabel();
        PanelUntungBulan1 = new javax.swing.JPanel();
        lblTampilGalon = new javax.swing.JLabel();
        Label_tampiUntung2 = new javax.swing.JLabel();
        Label_nama_keuntungan8 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        Label_nama_keuntungan4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBeliTanki1 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(542, 448));

        PanelUtama.setBackground(new java.awt.Color(219, 236, 248));
        PanelUtama.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelUtamaMouseMoved(evt);
            }
        });

        PanelUntungBulan.setBackground(new java.awt.Color(255, 255, 255));
        PanelUntungBulan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTampilUntung.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTampilUntung.setForeground(new java.awt.Color(98, 109, 120));
        lblTampilUntung.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTampilUntung.setText("0");
        lblTampilUntung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTampilUntungMouseClicked(evt);
            }
        });
        lblTampilUntung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTampilUntungKeyPressed(evt);
            }
        });
        PanelUntungBulan.add(lblTampilUntung, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 110, 27));

        Label_nama_keuntungan5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Label_nama_keuntungan5.setForeground(new java.awt.Color(44, 148, 230));
        Label_nama_keuntungan5.setText("Keuntungan Bulan Ini");
        PanelUntungBulan.add(Label_nama_keuntungan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Label_tampiUntung5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label_tampiUntung5.setForeground(new java.awt.Color(98, 109, 120));
        Label_tampiUntung5.setText("Rp.");
        Label_tampiUntung5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_tampiUntung5MouseClicked(evt);
            }
        });
        Label_tampiUntung5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Label_tampiUntung5KeyPressed(evt);
            }
        });
        PanelUntungBulan.add(Label_tampiUntung5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 40, 27));

        PanelInput.setBackground(new java.awt.Color(255, 255, 255));
        PanelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUbah.setBackground(new java.awt.Color(44, 148, 230));
        btnUbah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("UBAH");
        btnUbah.setBorder(null);
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        PanelInput.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 160, 40));

        btnTambah.setBackground(new java.awt.Color(44, 148, 230));
        btnTambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.setBorder(null);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        PanelInput.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 150, 40));

        txtTgl.setEditable(false);
        txtTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglActionPerformed(evt);
            }
        });
        PanelInput.add(txtTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 30, -1));

        txtJumlah.setEditable(false);
        txtJumlah.setBackground(new java.awt.Color(255, 255, 255));
        txtJumlah.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtJumlah.setForeground(new java.awt.Color(98, 109, 120));
        txtJumlah.setBorder(null);
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKeyTyped(evt);
            }
        });
        PanelInput.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 330, 30));

        txtGalon.setBackground(new java.awt.Color(255, 255, 255));
        txtGalon.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtGalon.setForeground(new java.awt.Color(98, 109, 120));
        txtGalon.setBorder(null);
        txtGalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGalonActionPerformed(evt);
            }
        });
        txtGalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGalonKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGalonKeyTyped(evt);
            }
        });
        PanelInput.add(txtGalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 330, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Jumlah");
        PanelInput.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 50, -1));

        txtId.setEditable(false);
        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtId.setForeground(new java.awt.Color(98, 109, 120));
        txtId.setBorder(null);
        PanelInput.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 330, 30));

        tanggal.setForeground(new java.awt.Color(98, 109, 120));
        tanggal.setName(""); // NOI18N
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        PanelInput.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 330, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Id:");
        PanelInput.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 30, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Jumlah Galon");
        PanelInput.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(146, 161, 175));
        jSeparator1.setForeground(new java.awt.Color(146, 161, 175));
        PanelInput.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 330, 10));

        jSeparator2.setBackground(new java.awt.Color(146, 161, 175));
        jSeparator2.setForeground(new java.awt.Color(146, 161, 175));
        PanelInput.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 330, 10));

        jSeparator3.setBackground(new java.awt.Color(146, 161, 175));
        jSeparator3.setForeground(new java.awt.Color(146, 161, 175));
        PanelInput.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 330, 10));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tgl :");
        PanelInput.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 30, -1));

        Label_nama_keuntungan11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Label_nama_keuntungan11.setForeground(new java.awt.Color(44, 148, 230));
        Label_nama_keuntungan11.setText("Atur Data Penjualan");
        PanelInput.add(Label_nama_keuntungan11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PanelTabel.setBackground(new java.awt.Color(255, 255, 255));
        PanelTabel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "null"
            }
        ));
        jScrollPane1.setViewportView(tablePenjualan);
        if (tablePenjualan.getColumnModel().getColumnCount() > 0) {
            tablePenjualan.getColumnModel().getColumn(0).setPreferredWidth(12);
        }

        PanelTabel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 622, 252));

        btnHapus.setBackground(new java.awt.Color(44, 148, 230));
        btnHapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        PanelTabel.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 200, 40));

        Label_nama_keuntungan9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Label_nama_keuntungan9.setForeground(new java.awt.Color(44, 148, 230));
        Label_nama_keuntungan9.setText("Tabel Penjualan");
        PanelTabel.add(Label_nama_keuntungan9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PanelUntungBulan3.setBackground(new java.awt.Color(255, 255, 255));
        PanelUntungBulan3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTampilTanki.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTampilTanki.setForeground(new java.awt.Color(98, 109, 120));
        lblTampilTanki.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTampilTanki.setText("0");
        lblTampilTanki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTampilTankiMouseClicked(evt);
            }
        });
        lblTampilTanki.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTampilTankiKeyPressed(evt);
            }
        });
        PanelUntungBulan3.add(lblTampilTanki, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, 27));

        Label_nama_keuntungan10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Label_nama_keuntungan10.setForeground(new java.awt.Color(44, 148, 230));
        Label_nama_keuntungan10.setText("Total Harga Tanki yang Dibeli");
        PanelUntungBulan3.add(Label_nama_keuntungan10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Label_tampiUntung6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label_tampiUntung6.setForeground(new java.awt.Color(98, 109, 120));
        Label_tampiUntung6.setText("Rp.");
        Label_tampiUntung6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_tampiUntung6MouseClicked(evt);
            }
        });
        Label_tampiUntung6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Label_tampiUntung6KeyPressed(evt);
            }
        });
        PanelUntungBulan3.add(Label_tampiUntung6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 40, 27));

        PanelUntungBulan4.setBackground(new java.awt.Color(255, 255, 255));
        PanelUntungBulan4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_tampiUntung3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label_tampiUntung3.setForeground(new java.awt.Color(98, 109, 120));
        Label_tampiUntung3.setText("Tanki");
        Label_tampiUntung3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_tampiUntung3MouseClicked(evt);
            }
        });
        Label_tampiUntung3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Label_tampiUntung3KeyPressed(evt);
            }
        });
        PanelUntungBulan4.add(Label_tampiUntung3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 27));

        lblTampilTankiSatuan.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTampilTankiSatuan.setForeground(new java.awt.Color(98, 109, 120));
        lblTampilTankiSatuan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTampilTankiSatuan.setText("0");
        lblTampilTankiSatuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTampilTankiSatuanMouseClicked(evt);
            }
        });
        lblTampilTankiSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTampilTankiSatuanKeyPressed(evt);
            }
        });
        PanelUntungBulan4.add(lblTampilTankiSatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 100, 27));

        Label_nama_keuntungan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Label_nama_keuntungan.setForeground(new java.awt.Color(44, 148, 230));
        Label_nama_keuntungan.setText("Jumlah Tanki Bulan Ini");
        PanelUntungBulan4.add(Label_nama_keuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PanelUntungBulan1.setBackground(new java.awt.Color(255, 255, 255));
        PanelUntungBulan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTampilGalon.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTampilGalon.setForeground(new java.awt.Color(98, 109, 120));
        lblTampilGalon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTampilGalon.setText("0");
        lblTampilGalon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTampilGalonMouseClicked(evt);
            }
        });
        lblTampilGalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTampilGalonKeyPressed(evt);
            }
        });
        PanelUntungBulan1.add(lblTampilGalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 103, 110, 27));

        Label_tampiUntung2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Label_tampiUntung2.setForeground(new java.awt.Color(98, 109, 120));
        Label_tampiUntung2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_tampiUntung2.setText("Galon");
        Label_tampiUntung2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_tampiUntung2MouseClicked(evt);
            }
        });
        Label_tampiUntung2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Label_tampiUntung2KeyPressed(evt);
            }
        });
        PanelUntungBulan1.add(Label_tampiUntung2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 103, -1, 27));

        Label_nama_keuntungan8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Label_nama_keuntungan8.setForeground(new java.awt.Color(44, 148, 230));
        Label_nama_keuntungan8.setText("Galon Terjual Bulan Ini");
        PanelUntungBulan1.add(Label_nama_keuntungan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addComponent(PanelUntungBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelUntungBulan1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PanelInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelUtamaLayout.createSequentialGroup()
                            .addComponent(PanelUntungBulan3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(PanelUntungBulan4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(PanelTabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(49, 49, 49))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelUntungBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelUntungBulan1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelUntungBulan3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelUntungBulan4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(PanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(PanelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(PanelUtama);

        PanelMenu.setBackground(new java.awt.Color(44, 148, 230));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nama_keuntungan4.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Label_nama_keuntungan4.setForeground(new java.awt.Color(255, 255, 255));
        Label_nama_keuntungan4.setText("RizkyBaru");
        PanelMenu.add(Label_nama_keuntungan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RizkyBaruApps V 1.0");
        PanelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 970, 130, 20));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ubah Harga");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 167, 40));

        btnPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Cetak Laporan");
        btnPrint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnPrint.setContentAreaFilled(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        PanelMenu.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 167, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Logout");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 910, 167, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard");
        PanelMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 20));

        btnBeliTanki1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBeliTanki1.setForeground(new java.awt.Color(255, 255, 255));
        btnBeliTanki1.setText("Beli Air Tangki");
        btnBeliTanki1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnBeliTanki1.setContentAreaFilled(false);
        btnBeliTanki1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliTanki1ActionPerformed(evt);
            }
        });
        PanelMenu.add(btnBeliTanki1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 167, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 271, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 823, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        controller.deletePenjualan(this);
        
        //ambil value dari tabel
        tampilUntung();
        tampilGalon();
        tampilTankiSatuan();
        tampilTanki();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void lblTampilTankiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTampilTankiKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblTampilTankiKeyPressed

    private void lblTampilTankiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTampilTankiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblTampilTankiMouseClicked

    private void txtJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyTyped
        // TODO add your handling code here:
        char ketikan = evt.getKeyChar();
        if (!(Character.isDigit(ketikan))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtJumlahKeyTyped

    private void txtGalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGalonKeyTyped
        // TODO add your handling code here:
        char ketikan = evt.getKeyChar();
        if (!(Character.isDigit(ketikan))) {
            evt.consume();
        }

    }//GEN-LAST:event_txtGalonKeyTyped

    private void txtGalonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGalonKeyReleased
        // TODO add your handling code here:
        Integer ketikGalon,jumlah;
        Integer hargaGalon = ambilHargaGalon();
        
        
        ketikGalon = Integer.parseInt(txtGalon.getText());
        jumlah = ketikGalon * hargaGalon;
        txtJumlah.setText(Integer.toString(jumlah));
    }//GEN-LAST:event_txtGalonKeyReleased

    private void txtGalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGalonActionPerformed

    private void txtTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        controller.insertPenjualan(this);
        
        //ambil value dari tabel
        tampilUntung();
        tampilGalon();
        tampilTankiSatuan();
        tampilTanki();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        controller.updatePenjualan(this);
        

    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        
        try{
 
      Class.forName("com.mysql.jdbc.Driver");
       Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lat_rizkybaru","root","");
       String reportPath = "C:\\Users\\MSI GF63\\Documents\\GitHub\\RizkyBaru\\src\\view\\ReportPenjualan.jrxml";
       JasperReport jr = JasperCompileManager.compileReport(reportPath);
       JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
       JasperViewer.viewReport(jp);
       con.close();
}
 
catch(Exception ex)
{
    ex.printStackTrace();
}
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void lblTampilUntungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTampilUntungMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilUntungMouseClicked

    private void lblTampilUntungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTampilUntungKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilUntungKeyPressed

    private void Label_tampiUntung5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_tampiUntung5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung5MouseClicked

    private void Label_tampiUntung5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Label_tampiUntung5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung5KeyPressed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void lblTampilGalonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTampilGalonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilGalonMouseClicked

    private void lblTampilGalonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTampilGalonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilGalonKeyPressed

    private void Label_tampiUntung2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Label_tampiUntung2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung2KeyPressed

    private void Label_tampiUntung2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_tampiUntung2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung2MouseClicked

    private void Label_tampiUntung3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_tampiUntung3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung3MouseClicked

    private void Label_tampiUntung3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Label_tampiUntung3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung3KeyPressed

    private void lblTampilTankiSatuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTampilTankiSatuanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilTankiSatuanMouseClicked

    private void lblTampilTankiSatuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTampilTankiSatuanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilTankiSatuanKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       updateHarga harga = new updateHarga();
       harga.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
        Calendar cals = Calendar.getInstance();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        tanggal.setFormats(dateFormat);
        DateFormat sysDate = new SimpleDateFormat("yyyy-MM-dd");
        String date_to_store = sysDate.format(tanggal.getDate());
        txtTgl.setText(date_to_store);
    }//GEN-LAST:event_tanggalActionPerformed

    private void Label_tampiUntung6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_tampiUntung6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung6MouseClicked

    private void Label_tampiUntung6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Label_tampiUntung6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung6KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        LoginView login = new LoginView();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnBeliTanki1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliTanki1ActionPerformed
        // TODO add your handling code here:
        
        isiTanki isi = new isiTanki();
        isi.setVisible(true);
        
        
    }//GEN-LAST:event_btnBeliTanki1ActionPerformed

    private void PanelUtamaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelUtamaMouseMoved
        // TODO add your handling code here:
        
         //ambil value dari tabel
        tampilUntung();
        tampilGalon();
        tampilTankiSatuan();
        tampilTanki();
    }//GEN-LAST:event_PanelUtamaMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_nama_keuntungan;
    private javax.swing.JLabel Label_nama_keuntungan10;
    private javax.swing.JLabel Label_nama_keuntungan11;
    private javax.swing.JLabel Label_nama_keuntungan4;
    private javax.swing.JLabel Label_nama_keuntungan5;
    private javax.swing.JLabel Label_nama_keuntungan8;
    private javax.swing.JLabel Label_nama_keuntungan9;
    private javax.swing.JLabel Label_tampiUntung2;
    private javax.swing.JLabel Label_tampiUntung3;
    private javax.swing.JLabel Label_tampiUntung5;
    private javax.swing.JLabel Label_tampiUntung6;
    private javax.swing.JPanel PanelInput;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelTabel;
    private javax.swing.JPanel PanelUntungBulan;
    private javax.swing.JPanel PanelUntungBulan1;
    private javax.swing.JPanel PanelUntungBulan3;
    private javax.swing.JPanel PanelUntungBulan4;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JButton btnBeliTanki1;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblTampilGalon;
    private javax.swing.JLabel lblTampilTanki;
    private javax.swing.JLabel lblTampilTankiSatuan;
    private javax.swing.JLabel lblTampilUntung;
    private javax.swing.JTable tablePenjualan;
    private org.jdesktop.swingx.JXDatePicker tanggal;
    private javax.swing.JTextField txtGalon;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTgl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(PenjualanModel model) {
        txtId.setText(model.getId() + "");
        txtTgl.setText(String.valueOf(model.getTgl()));
        txtGalon.setText(String.valueOf(model.getGalon()));
        txtJumlah.setText(String.valueOf(model.getJumlah()));
    }

    @Override
    public void onInsert(Penjualan Penjualan) {

        tabelModel.add(Penjualan);
    }

    @Override
    public void onUpdate(Penjualan Penjualan) {
        int index = tablePenjualan.getSelectedRow();
        tabelModel.set(index, Penjualan);

    }

    @Override
    public void onDelete() {
        int index = tablePenjualan.getSelectedRow();
        tabelModel.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Penjualan model = tabelModel.get(tablePenjualan.getSelectedRow());
            txtId.setText(model.getId() + "");
            txtTgl.setText(model.getTgl());
            txtTgl.setText(String.valueOf(model.getTgl()));
            txtGalon.setText(String.valueOf(model.getGalon()));
            txtJumlah.setText(String.valueOf(model.getJumlah()));
        } catch (IndexOutOfBoundsException exception) {
        }

    }

    public void loadDatabase() throws SQLException, PenjualanException {
        PenjualanDao dao = RizkyBaruDatabase.getPenjualanDao();
        tabelModel.setList(dao.selectAllPenjualan());
    }

    private String format(JXDatePicker tanggal) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    
private Connection con;

//class manipulasi database
    
    private Integer ambilHargaGalon(){
        
        this.con=con;
        String selectUntung = "SELECT harga FROM harga_galon WHERE id_harga=1" ;
        Statement statement = null;
        Integer hargaInt;
        String ambilKolomHarga;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            ambilKolomHarga = result.getString("harga");
            hargaInt = Integer.parseInt(ambilKolomHarga);
            
            
            
            return hargaInt;
            
            
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return hargaInt = 0;
        }
    }

    public String tampilUntung() {
        
        this.con=con;
        String selectUntung = "SELECT SUM(Jumlah) FROM `Penjualan` WHERE Tgl LIKE '"+ hariIni()+"%' " ;
        Statement statement = null;
        Integer untung,total,tanki;
        String tampil_total,tankicek,untungKosong;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            untung = Integer.parseInt(result.getString("SUM(Jumlah)"));
            
            untungKosong = Integer.toString(untung);
            tankicek = tampilTanki();
            
            if (tankicek == null) {
                
                lblTampilUntung.setText(untungKosong);
                return tampil_total = untungKosong;
                
            } else {
                tanki = Integer.parseInt(tankicek);
                total = untung - tanki;
                tampil_total = Integer.toString(total);
            
                 lblTampilUntung.setText(tampil_total);
            return tampil_total;
            }
            
            
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return tampil_total = "0";
        }
        

    }

    
    public String tampilTankiSatuan() {
        
        this.con=con;
        String selectUntung = "SELECT COUNT(*) FROM `beli_tanki`" ;
        Statement statement = null;
        Integer total;
        String ambilKolomTanki;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            ambilKolomTanki = result.getString("COUNT(*)");
            
            if (ambilKolomTanki == "") {
                
                lblTampilTankiSatuan.setText("0");
                return "0";
                
            } else {
                lblTampilTankiSatuan.setText(ambilKolomTanki);
                return ambilKolomTanki;
            }
            
            
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return ambilKolomTanki = "0";
        }
        

    }
    
    public String tampilGalon() {
        
        this.con=con;
        String selectUntung = "SELECT SUM(galon_terjual) FROM `Penjualan` WHERE Tgl LIKE '"+ hariIni()+"%' " ;
        Statement statement = null;
        Integer total,tanki;
        String tampil_total,ambilGalon;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            ambilGalon = result.getString("SUM(galon_terjual)");
            
            if (ambilGalon == "") {
                
                lblTampilGalon.setText("0");
                return "0";
                
            } else {
                lblTampilGalon.setText(ambilGalon);
                return ambilGalon;
            }
            
            
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return tampil_total = "0";
        }
        

    }
    
    public String tampilTanki() {
        
        this.con=con;
        String selectUntung = "SELECT SUM(harga_tanki) FROM `beli_tanki` WHERE tanggal LIKE '"+ hariIni()+"%' " ;
        Statement statement = null;
        String tanki;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            tanki = result.getString("SUM(harga_tanki)");
            
            if (tanki == "") {
                JOptionPane.showMessageDialog(this , "Data Tanki Masih Kosong!");
                return tanki = "";
            } else { 
                lblTampilTanki.setText(tanki);
                return tanki;
            }
            
           
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return tanki = "";
        }
        

    }

        
    
     public void updateHarga(String harga) {
        
       
        this.con=con;
        String updateHarga = "UPDATE `harga_galon` SET `harga`=" +  harga   + " WHERE 1 ";
        Statement statement = null;
        try {
            
            statement = getConnection().createStatement();
            statement.executeUpdate(updateHarga);
            
            JOptionPane.showMessageDialog(this , "Berhasil Update Data Jadi ");
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            
        }

    }    
        
    public void isiTanki(String text) {
        
       
        this.con=con;
        String insertTanki = "INSERT INTO `beli_tanki`(`harga_tanki`, `tanggal`) VALUES ('"+ text +"' , '" + hariIniFull()  + "')";
        Statement statement = null;
        String tanki;
        try {
            
            statement = getConnection().createStatement();
            statement.executeUpdate(insertTanki);
            
            JOptionPane.showMessageDialog(this , "Berhasil Input Tanki");
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            
        }

    }
    
    private String hariIni() {
        Calendar cals = Calendar.getInstance();
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM");
       
        String hari_ini = formater.format(cals.getTime());
        return hari_ini;
    }
    
    private String hariIniFull() {
        Calendar cals = GregorianCalendar.getInstance();
        
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd"); 
       
        String hari_ini = formater.format(cals.getTime());  
        return hari_ini;
    }
}

