/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import controller.PenjualanController;
import database.RizkyBaruDatabase;
import static database.RizkyBaruDatabase.getConnection;
import entity.Penjualan;
import error.PenjualanException;
import event.PenjualanListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import model.PenjualanModel;
import model.TabelPenjualanModel;
import service.PenjualanDao;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import org.jdesktop.swingx.JXDatePicker;
import view.isiTanki;

/**
 *
 * @author Rizki Adam Kurniawan
 */
public class PenjualanVIew extends javax.swing.JPanel implements PenjualanListener, ListSelectionListener {

    private TabelPenjualanModel tabelModel;
    private PenjualanModel model;
    private PenjualanController controller;
    private Object jLabel;

    public PenjualanVIew() {
        tabelModel = new TabelPenjualanModel();

        model = new PenjualanModel();
        model.setListener(this);

        controller = new PenjualanController();
        controller.setModel(model);

        initComponents();
        tablePenjualan.getSelectionModel().addListSelectionListener(this);

        tablePenjualan.setModel(tabelModel);
        
        tampilUntung();
        tampilGalon();
        tampilTankiSatuan();
        
        txtTgl.setVisible(false);
        
       
    }

    public JTable getTablePenjualan() {
        return tablePenjualan;
    }

    public JTextField getTxtGalon() {
        return txtGalon;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public JTextField getTxtTgl() {
        return txtTgl;
    }

    public JTextField getTxtJumlah() {
        return txtJumlah;
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        PanelUtama = new javax.swing.JPanel();
        PanelUntungBulan = new javax.swing.JPanel();
        Label_nama_keuntungan = new javax.swing.JLabel();
        lblTampilUntung = new javax.swing.JLabel();
        PanelInput = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        txtTgl = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtGalon = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Label_nama_keuntungan2 = new javax.swing.JLabel();
        tanggal = new org.jdesktop.swingx.JXDatePicker();
        PanelUntungBulan2 = new javax.swing.JPanel();
        Label_nama_keuntungan5 = new javax.swing.JLabel();
        PanelTabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenjualan = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        Label_nama_keuntungan3 = new javax.swing.JLabel();
        PanelUntungBulan3 = new javax.swing.JPanel();
        Label_nama_keuntungan6 = new javax.swing.JLabel();
        lblTampilTanki = new javax.swing.JLabel();
        Label_tampiUntung5 = new javax.swing.JLabel();
        PanelUntungBulan4 = new javax.swing.JPanel();
        Label_nama_keuntungan7 = new javax.swing.JLabel();
        Label_tampiUntung3 = new javax.swing.JLabel();
        lblTampilTankiSatuan = new javax.swing.JLabel();
        PanelUntungBulan1 = new javax.swing.JPanel();
        Label_nama_keuntungan1 = new javax.swing.JLabel();
        lblTampilGalon = new javax.swing.JLabel();
        Label_tampiUntung2 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JPanel();
        Label_nama_keuntungan4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        btnBeliTanki = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(542, 448));

        PanelUtama.setBackground(new java.awt.Color(219, 236, 248));

        PanelUntungBulan.setBackground(new java.awt.Color(255, 255, 255));

        Label_nama_keuntungan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Label_nama_keuntungan.setText("Keuntungan Bulan Ini");

        lblTampilUntung.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTampilUntung.setText("0");
        lblTampilUntung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTampilUntungMouseClicked(evt);
            }
        });
        lblTampilUntung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTampilUntungKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PanelUntungBulanLayout = new javax.swing.GroupLayout(PanelUntungBulan);
        PanelUntungBulan.setLayout(PanelUntungBulanLayout);
        PanelUntungBulanLayout.setHorizontalGroup(
            PanelUntungBulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUntungBulanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUntungBulanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTampilUntung)
                .addGap(24, 24, 24))
        );
        PanelUntungBulanLayout.setVerticalGroup(
            PanelUntungBulanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUntungBulanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lblTampilUntung, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        PanelInput.setBackground(new java.awt.Color(255, 255, 255));
        PanelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        PanelInput.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        PanelInput.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        txtTgl.setEditable(false);
        txtTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglActionPerformed(evt);
            }
        });
        PanelInput.add(txtTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 30, -1));

        txtJumlah.setEditable(false);
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahKeyTyped(evt);
            }
        });
        PanelInput.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 242, 23));

        txtGalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGalonActionPerformed(evt);
            }
        });
        txtGalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGalonKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGalonKeyTyped(evt);
            }
        });
        PanelInput.add(txtGalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 242, 23));

        txtId.setEditable(false);
        PanelInput.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 121, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ID :");
        PanelInput.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 101, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tgl :");
        PanelInput.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 101, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Jumlah Galon:");
        PanelInput.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 101, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Jumlah :");
        PanelInput.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 101, -1));

        Label_nama_keuntungan2.setText("Ubah Data Penjualan");
        PanelInput.add(Label_nama_keuntungan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        tanggal.setName(""); // NOI18N
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        PanelInput.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 240, 23));

        PanelUntungBulan2.setBackground(new java.awt.Color(255, 255, 255));

        Label_nama_keuntungan5.setText("Galon Terjual Bulan Ini");

        javax.swing.GroupLayout PanelUntungBulan2Layout = new javax.swing.GroupLayout(PanelUntungBulan2);
        PanelUntungBulan2.setLayout(PanelUntungBulan2Layout);
        PanelUntungBulan2Layout.setHorizontalGroup(
            PanelUntungBulan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUntungBulan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan5)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        PanelUntungBulan2Layout.setVerticalGroup(
            PanelUntungBulan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUntungBulan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan5)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        PanelInput.add(PanelUntungBulan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -50, -1, -1));

        PanelTabel.setBackground(new java.awt.Color(255, 255, 255));

        tablePenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "null"
            }
        ));
        jScrollPane1.setViewportView(tablePenjualan);
        if (tablePenjualan.getColumnModel().getColumnCount() > 0) {
            tablePenjualan.getColumnModel().getColumn(0).setPreferredWidth(12);
        }

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        Label_nama_keuntungan3.setText("Tabel Penjualan");

        javax.swing.GroupLayout PanelTabelLayout = new javax.swing.GroupLayout(PanelTabel);
        PanelTabel.setLayout(PanelTabelLayout);
        PanelTabelLayout.setHorizontalGroup(
            PanelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTabelLayout.createSequentialGroup()
                .addGroup(PanelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTabelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PanelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHapus)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelTabelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_nama_keuntungan3)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelTabelLayout.setVerticalGroup(
            PanelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addGap(43, 43, 43))
        );

        PanelUntungBulan3.setBackground(new java.awt.Color(255, 255, 255));

        Label_nama_keuntungan6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Label_nama_keuntungan6.setText("Jumlah Pembelian Tanki");

        lblTampilTanki.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTampilTanki.setText("0");
        lblTampilTanki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTampilTankiMouseClicked(evt);
            }
        });
        lblTampilTanki.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTampilTankiKeyPressed(evt);
            }
        });

        Label_tampiUntung5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label_tampiUntung5.setText("Rp.");
        Label_tampiUntung5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_tampiUntung5MouseClicked(evt);
            }
        });
        Label_tampiUntung5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Label_tampiUntung5KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PanelUntungBulan3Layout = new javax.swing.GroupLayout(PanelUntungBulan3);
        PanelUntungBulan3.setLayout(PanelUntungBulan3Layout);
        PanelUntungBulan3Layout.setHorizontalGroup(
            PanelUntungBulan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUntungBulan3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUntungBulan3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_tampiUntung5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTampilTanki)
                .addGap(23, 23, 23))
        );
        PanelUntungBulan3Layout.setVerticalGroup(
            PanelUntungBulan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUntungBulan3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(PanelUntungBulan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTampilTanki, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_tampiUntung5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        PanelUntungBulan4.setBackground(new java.awt.Color(255, 255, 255));

        Label_nama_keuntungan7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Label_nama_keuntungan7.setText("Jumlah Pembelian Tanki Bulan Ini");

        Label_tampiUntung3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label_tampiUntung3.setText("Tanki");
        Label_tampiUntung3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_tampiUntung3MouseClicked(evt);
            }
        });
        Label_tampiUntung3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Label_tampiUntung3KeyPressed(evt);
            }
        });

        lblTampilTankiSatuan.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTampilTankiSatuan.setText("0");
        lblTampilTankiSatuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTampilTankiSatuanMouseClicked(evt);
            }
        });
        lblTampilTankiSatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTampilTankiSatuanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PanelUntungBulan4Layout = new javax.swing.GroupLayout(PanelUntungBulan4);
        PanelUntungBulan4.setLayout(PanelUntungBulan4Layout);
        PanelUntungBulan4Layout.setHorizontalGroup(
            PanelUntungBulan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUntungBulan4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan7)
                .addContainerGap(146, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUntungBulan4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTampilTankiSatuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_tampiUntung3)
                .addGap(18, 18, 18))
        );
        PanelUntungBulan4Layout.setVerticalGroup(
            PanelUntungBulan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUntungBulan4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelUntungBulan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_tampiUntung3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTampilTankiSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        PanelUntungBulan1.setBackground(new java.awt.Color(255, 255, 255));

        Label_nama_keuntungan1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Label_nama_keuntungan1.setText("Galon Terjual Bulan Ini");

        lblTampilGalon.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTampilGalon.setText("0");
        lblTampilGalon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTampilGalonMouseClicked(evt);
            }
        });
        lblTampilGalon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblTampilGalonKeyPressed(evt);
            }
        });

        Label_tampiUntung2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label_tampiUntung2.setText("Galon");
        Label_tampiUntung2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_tampiUntung2MouseClicked(evt);
            }
        });
        Label_tampiUntung2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Label_tampiUntung2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PanelUntungBulan1Layout = new javax.swing.GroupLayout(PanelUntungBulan1);
        PanelUntungBulan1.setLayout(PanelUntungBulan1Layout);
        PanelUntungBulan1Layout.setHorizontalGroup(
            PanelUntungBulan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUntungBulan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUntungBulan1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTampilGalon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_tampiUntung2)
                .addGap(16, 16, 16))
        );
        PanelUntungBulan1Layout.setVerticalGroup(
            PanelUntungBulan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUntungBulan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_nama_keuntungan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(PanelUntungBulan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTampilGalon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_tampiUntung2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelUntungBulan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelUntungBulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelUntungBulan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelUntungBulan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42))
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PanelTabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 42, Short.MAX_VALUE))))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelUntungBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelUntungBulan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelUntungBulan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelUntungBulan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(PanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jScrollPane2.setViewportView(PanelUtama);

        PanelMenu.setBackground(new java.awt.Color(44, 148, 230));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nama_keuntungan4.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        Label_nama_keuntungan4.setForeground(new java.awt.Color(255, 255, 255));
        Label_nama_keuntungan4.setText("RizkyBaru");
        PanelMenu.add(Label_nama_keuntungan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");
        PanelMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 20));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ubah Harga");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 167, 26));

        btnBeliTanki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBeliTanki.setForeground(new java.awt.Color(255, 255, 255));
        btnBeliTanki.setText("Beli Air Tangki");
        btnBeliTanki.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBeliTanki.setContentAreaFilled(false);
        btnBeliTanki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliTankiActionPerformed(evt);
            }
        });
        PanelMenu.add(btnBeliTanki, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 167, 26));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Logout");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.setContentAreaFilled(false);
        PanelMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 167, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 245, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 799, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        controller.deletePenjualan(this);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void lblTampilTankiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTampilTankiKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblTampilTankiKeyPressed

    private void lblTampilTankiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTampilTankiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblTampilTankiMouseClicked

    private void txtJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyTyped
        // TODO add your handling code here:
        char ketikan = evt.getKeyChar();
        if (!(Character.isDigit(ketikan))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtJumlahKeyTyped

    private void txtGalonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGalonKeyTyped
        // TODO add your handling code here:
        char ketikan = evt.getKeyChar();
        if (!(Character.isDigit(ketikan))) {
            evt.consume();
        }

    }//GEN-LAST:event_txtGalonKeyTyped

    private void txtGalonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGalonKeyReleased
        // TODO add your handling code here:
        Integer ketikGalon,jumlah;
        Integer hargaGalon = ambilHargaGalon();
        
        
        ketikGalon = Integer.parseInt(txtGalon.getText());
        jumlah = ketikGalon * hargaGalon;
        txtJumlah.setText(Integer.toString(jumlah));
    }//GEN-LAST:event_txtGalonKeyReleased

    private void txtGalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGalonActionPerformed

    private void txtTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
        Calendar cals = Calendar.getInstance();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        tanggal.setFormats(dateFormat);
        DateFormat sysDate = new SimpleDateFormat("yyyy-MM-dd");
        String date_to_store = sysDate.format(tanggal.getDate());
        txtTgl.setText(date_to_store);
    }//GEN-LAST:event_tanggalActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        controller.insertPenjualan(this);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        controller.updatePenjualan(this);
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBeliTankiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliTankiActionPerformed
        // TODO add your handling code here:
        
        isiTanki isitank = new isiTanki();
        isitank.setVisible(true);
        
    }//GEN-LAST:event_btnBeliTankiActionPerformed

    private void lblTampilUntungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTampilUntungMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilUntungMouseClicked

    private void lblTampilUntungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTampilUntungKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilUntungKeyPressed

    private void Label_tampiUntung5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_tampiUntung5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung5MouseClicked

    private void Label_tampiUntung5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Label_tampiUntung5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung5KeyPressed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void lblTampilGalonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTampilGalonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilGalonMouseClicked

    private void lblTampilGalonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTampilGalonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilGalonKeyPressed

    private void Label_tampiUntung2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Label_tampiUntung2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung2KeyPressed

    private void Label_tampiUntung2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_tampiUntung2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung2MouseClicked

    private void Label_tampiUntung3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_tampiUntung3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung3MouseClicked

    private void Label_tampiUntung3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Label_tampiUntung3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tampiUntung3KeyPressed

    private void lblTampilTankiSatuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTampilTankiSatuanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilTankiSatuanMouseClicked

    private void lblTampilTankiSatuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblTampilTankiSatuanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTampilTankiSatuanKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       updateHarga harga = new updateHarga();
       harga.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_nama_keuntungan;
    private javax.swing.JLabel Label_nama_keuntungan1;
    private javax.swing.JLabel Label_nama_keuntungan2;
    private javax.swing.JLabel Label_nama_keuntungan3;
    private javax.swing.JLabel Label_nama_keuntungan4;
    private javax.swing.JLabel Label_nama_keuntungan5;
    private javax.swing.JLabel Label_nama_keuntungan6;
    private javax.swing.JLabel Label_nama_keuntungan7;
    private javax.swing.JLabel Label_tampiUntung2;
    private javax.swing.JLabel Label_tampiUntung3;
    private javax.swing.JLabel Label_tampiUntung5;
    private javax.swing.JPanel PanelInput;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelTabel;
    private javax.swing.JPanel PanelUntungBulan;
    private javax.swing.JPanel PanelUntungBulan1;
    private javax.swing.JPanel PanelUntungBulan2;
    private javax.swing.JPanel PanelUntungBulan3;
    private javax.swing.JPanel PanelUntungBulan4;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JButton btnBeliTanki;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTampilGalon;
    private javax.swing.JLabel lblTampilTanki;
    private javax.swing.JLabel lblTampilTankiSatuan;
    private javax.swing.JLabel lblTampilUntung;
    private javax.swing.JTable tablePenjualan;
    private org.jdesktop.swingx.JXDatePicker tanggal;
    private javax.swing.JTextField txtGalon;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTgl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(PenjualanModel model) {
        txtId.setText(model.getId() + "");
        txtTgl.setText(String.valueOf(model.getTgl()));
        txtGalon.setText(String.valueOf(model.getGalon()));
        txtJumlah.setText(String.valueOf(model.getJumlah()));
    }

    @Override
    public void onInsert(Penjualan Penjualan) {

        tabelModel.add(Penjualan);
    }

    @Override
    public void onUpdate(Penjualan Penjualan) {
        int index = tablePenjualan.getSelectedRow();
        tabelModel.set(index, Penjualan);

    }

    @Override
    public void onDelete() {
        int index = tablePenjualan.getSelectedRow();
        tabelModel.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Penjualan model = tabelModel.get(tablePenjualan.getSelectedRow());
            txtId.setText(model.getId() + "");
            txtTgl.setText(model.getTgl());
            txtTgl.setText(String.valueOf(model.getTgl()));
            txtGalon.setText(String.valueOf(model.getGalon()));
            txtJumlah.setText(String.valueOf(model.getJumlah()));
        } catch (IndexOutOfBoundsException exception) {
        }

    }

    public void loadDatabase() throws SQLException, PenjualanException {
        PenjualanDao dao = RizkyBaruDatabase.getPenjualanDao();
        tabelModel.setList(dao.selectAllPenjualan());
    }

    private String format(JXDatePicker tanggal) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    
private Connection con;

//class manipulasi database
    
    private Integer ambilHargaGalon(){
        
        this.con=con;
        String selectUntung = "SELECT harga FROM harga_galon WHERE id_harga=1" ;
        Statement statement = null;
        Integer hargaInt;
        String ambilKolomHarga;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            ambilKolomHarga = result.getString("harga");
            hargaInt = Integer.parseInt(ambilKolomHarga);
            
            
            
            return hargaInt;
            
            
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return hargaInt = 0;
        }
    }

    private String tampilUntung() {
        
        this.con=con;
        String selectUntung = "SELECT SUM(Jumlah) FROM `Penjualan` WHERE Tgl LIKE '"+ hariIni()+"%' " ;
        Statement statement = null;
        Integer untung,total,tanki;
        String tampil_total,tankicek,untungKosong;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            untung = Integer.parseInt(result.getString("SUM(Jumlah)"));
            
            untungKosong = Integer.toString(untung);
            tankicek = tampilTanki();
            
            if (tankicek == null) {
                
                lblTampilUntung.setText(untungKosong);
                return tampil_total = untungKosong;
                
            } else {
                tanki = Integer.parseInt(tankicek);
                total = untung - tanki;
                tampil_total = Integer.toString(total);
            
                 lblTampilUntung.setText(tampil_total);
            return tampil_total;
            }
            
            
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return tampil_total = "0";
        }
        

    }

    
    private String tampilTankiSatuan() {
        
        this.con=con;
        String selectUntung = "SELECT COUNT(*) FROM `beli_tanki`" ;
        Statement statement = null;
        Integer total;
        String ambilKolomTanki;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            ambilKolomTanki = result.getString("COUNT(*)");
            
            if (ambilKolomTanki == "") {
                
                lblTampilTankiSatuan.setText("0");
                return "0";
                
            } else {
                lblTampilTankiSatuan.setText(ambilKolomTanki);
                return ambilKolomTanki;
            }
            
            
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return ambilKolomTanki = "0";
        }
        

    }
    
    private String tampilGalon() {
        
        this.con=con;
        String selectUntung = "SELECT SUM(galon_terjual) FROM `Penjualan` WHERE Tgl LIKE '"+ hariIni()+"%' " ;
        Statement statement = null;
        Integer total,tanki;
        String tampil_total,ambilGalon;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            ambilGalon = result.getString("SUM(galon_terjual)");
            
            if (ambilGalon == "") {
                
                lblTampilGalon.setText("0");
                return "0";
                
            } else {
                lblTampilGalon.setText(ambilGalon);
                return ambilGalon;
            }
            
            
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return tampil_total = "0";
        }
        

    }
    
    private String tampilTanki() {
        
        this.con=con;
        String selectUntung = "SELECT SUM(harga_tanki) FROM `beli_tanki` WHERE tanggal LIKE '"+ hariIni()+"%' " ;
        Statement statement = null;
        String tanki;
        try {
            
            statement = getConnection().createStatement();

            ResultSet result = statement.executeQuery(selectUntung);
            result.next();
            tanki = result.getString("SUM(harga_tanki)");
            
            if (tanki == "") {
                JOptionPane.showMessageDialog(this , "Data Tanki Masih Kosong!");
                return tanki = "";
            } else { 
                lblTampilTanki.setText(tanki);
                return tanki;
            }
            
           
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            return tanki = "";
        }
        

    }

        
    
     public void updateHarga(String harga) {
        
       
        this.con=con;
        String updateHarga = "UPDATE `harga_galon` SET `harga`=" +  harga   + " WHERE 1 ";
        Statement statement = null;
        try {
            
            statement = getConnection().createStatement();
            statement.executeUpdate(updateHarga);
            
            JOptionPane.showMessageDialog(this , "Berhasil Update Data Jadi ");
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            
        }

    }    
        
    public void isiTanki(String text) {
        
       
        this.con=con;
        String insertTanki = "INSERT INTO `beli_tanki`(`harga_tanki`, `tanggal`) VALUES ('"+ text +"' , '" + hariIniFull()  + "')";
        Statement statement = null;
        String tanki;
        try {
            
            statement = getConnection().createStatement();
            statement.executeUpdate(insertTanki);
            
            JOptionPane.showMessageDialog(this , "Berhasil Input Tanki");
        } 
        
        
        catch (SQLException exception) {
            showMessageDialog(null, exception);
            
        }

    }
    
    private String hariIni() {
        Calendar cals = Calendar.getInstance();
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM");
       
        String hari_ini = formater.format(cals.getTime());
        return hari_ini;
    }
    
    private String hariIniFull() {
        Calendar cals = GregorianCalendar.getInstance();
        
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd"); 
       
        String hari_ini = formater.format(cals.getTime());  
        return hari_ini;
    }
}

